/* Generated by Yosys 0.38 (git sha1 543faed9c8c, clang++ 17.0.6 -fPIC -Os) */

module tristate_test(in, en, out);
  wire _0_;
  input en;
  wire en;
  input in;
  wire in;
  output out;
  wire out;
  sky130_fd_sc_hd__inv_2 _1_ (
    .A(en),
    .Y(_0_)
  );
  sky130_fd_sc_hd__ebufn_2 _2_ (
    .A(in),
    .TE_B(_0_),
    .Z(out)
  );
endmodule
